name: BuildVerifier

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r benchmark_requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Compile LaTeX
        run: |
          latexmk -halt-on-error book.tex > build.log || exit 1
          if grep -i 'undefined' build.log; then
            echo 'Undefined references found'
            exit 1
          fi

